name: Run tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          cache-dependency-path: |
            example/package-lock.json
            package-lock.json
          node-version: "18.x"
          cache: "npm"
      - name: Install & Build
        run: |
          npm i
          npm ci
          cd example && npm i && cd ..
          npm run build
      - name: pkg-pr-new
        run: npx pkg-pr-new publish . || true
      - name: Test
        run: npm run test
